In [1]:
import pandas as pd
import numpy as np
import datetime
from ml_investing_wne import config

In [2]:
backtest = pd.read_csv('/Users/i0495036/Documents/sandbox/ml_investing_wne/src/ml_investing_wne/models/backtest_ETHUSDT.csv', parse_dates=['datetime'])

In [3]:
backtest.head(10)

,Unnamed: 0,open,close,high,low,volume,y_pred,to_keep_x,SMA_5,EMA_5,...,barrier_touched,barrier_touched_date,top_barrier,bottom_barrier,time_step,barrier_touched_date_lag,to_keep_y,trade,budget,transaction
0,0,3364.99,3314.78,3388.41,3302.20,107714.8465,1,1.0,3384.336,3369.243540,...,top,2022-04-02 00:51:00,3480.5190,3149.0410,6.0,2022-04-03 22:02:00,1.0,0.0,94.762500,sell
1,1,3314.78,3245.88,3317.21,3244.05,210010.0888,1,1.0,3348.920,3328.122360,...,top,2022-04-01 17:43:00,3408.1740,3083.5860,4.0,2022-04-02 00:51:00,1.0,0.5,NaN,NaN
2,2,3245.89,3281.68,3281.68,3210.68,105066.6572,1,1.0,3329.842,3312.641573,...,top,2022-04-01 17:43:00,3445.7640,3117.5960,3.0,2022-04-01 17:43:00,1.0,0.0,NaN,NaN
3,3,3281.68,3330.82,3332.29,3262.22,108858.9159,1,1.0,3307.630,3318.701049,...,top,2022-04-02 00:51:00,3497.3610,3164.2790,3.0,2022-04-01 17:43:00,1.0,0.0,NaN,NaN
4,4,3330.83,3398.66,3400.00,3330.01,68984.0658,1,1.0,3314.364,3345.354033,...,top,2022-04-04 00:01:00,3568.5930,3228.7270,9.0,2022-04-02 00:51:00,1.0,0.0,NaN,NaN
5,5,3398.67,3466.98,3469.26,3398.00,117496.7928,0,1.0,3344.804,3385.896022,...,bottom,2022-04-06 01:19:00,3640.3290,3293.6310,16.0,2022-04-04 00:01:00,1.0,0.5,NaN,NaN
6,6,3466.98,3504.41,3509.77,3426.41,112752.2679,0,1.0,3396.510,3425.400681,...,bottom,2022-04-06 00:14:00,3679.6305,3329.1895,14.0,2022-04-06 01:19:00,1.0,0.5,94.525594,No trade
7,7,3504.42,3451.47,3525.13,3445.00,66491.4051,0,1.0,3430.468,3434.090454,...,bottom,2022-04-06 01:19:00,3624.0435,3278.8965,14.0,2022-04-06 00:14:00,1.0,0.5,94.525594,No trade
8,8,3451.47,3524.94,3528.34,3451.47,163721.0202,0,1.0,3469.292,3464.373636,...,bottom,2022-04-06 00:14:00,3701.1870,3348.6930,12.0,2022-04-06 01:19:00,1.0,0.0,99.003744,sell
9,9,3524.95,3457.01,3532.20,3456.70,74831.2278,0,1.0,3480.962,3461.919091,...,bottom,2022-04-06 01:19:00,3629.8605,3284.1595,12.0,2022-04-06 00:14:00,1.0,0.0,NaN,NaN

In [4]:
trades = backtest[backtest['transaction'].notna()]

In [5]:
trades.head(10)

,Unnamed: 0,open,close,high,low,volume,y_pred,to_keep_x,SMA_5,EMA_5,...,barrier_touched,barrier_touched_date,top_barrier,bottom_barrier,time_step,barrier_touched_date_lag,to_keep_y,trade,budget,transaction
0,0,3364.99,3314.78,3388.41,3302.20,107714.8465,1,1.0,3384.336,3369.243540,...,top,2022-04-02 00:51:00,3480.5190,3149.0410,6.0,2022-04-03 22:02:00,1.0,0.0,94.762500,sell
6,6,3466.98,3504.41,3509.77,3426.41,112752.2679,0,1.0,3396.510,3425.400681,...,bottom,2022-04-06 00:14:00,3679.6305,3329.1895,14.0,2022-04-06 01:19:00,1.0,0.5,94.525594,No trade
7,7,3504.42,3451.47,3525.13,3445.00,66491.4051,0,1.0,3430.468,3434.090454,...,bottom,2022-04-06 01:19:00,3624.0435,3278.8965,14.0,2022-04-06 00:14:00,1.0,0.5,94.525594,No trade
8,8,3451.47,3524.94,3528.34,3451.47,163721.0202,0,1.0,3469.292,3464.373636,...,bottom,2022-04-06 00:14:00,3701.1870,3348.6930,12.0,2022-04-06 01:19:00,1.0,0.0,99.003744,sell
20,20,3387.22,3316.95,3392.98,3313.00,34695.0981,0,1.0,3429.788,3400.701830,...,bottom,2022-04-07 04:52:00,3482.7975,3151.1025,9.0,2022-04-06 16:39:00,1.0,0.5,98.756234,No trade
21,21,3316.94,3343.56,3345.41,3268.00,72661.2489,0,1.0,3389.624,3381.654553,...,bottom,2022-04-06 19:02:00,3510.7380,3176.3820,6.0,2022-04-07 04:52:00,1.0,0.5,98.756234,No trade
22,22,3343.57,3305.10,3373.64,3304.34,150836.0865,0,1.0,3354.844,3356.136369,...,bottom,2022-04-11 09:34:00,3470.3550,3139.8450,20.0,2022-04-06 19:02:00,1.0,0.5,98.756234,No trade
23,23,3305.11,3256.40,3326.19,3256.00,91325.9398,0,1.0,3321.848,3322.890913,...,bottom,2022-04-11 10:03:00,3419.2200,3093.5800,20.0,2022-04-11 09:34:00,1.0,0.5,98.756234,No trade
24,24,3256.27,3190.33,3273.98,3182.00,155434.7259,0,1.0,3282.468,3278.703942,...,bottom,2022-04-11 13:32:00,3349.8465,3030.8135,20.0,2022-04-11 10:03:00,1.0,1.0,93.583877,buy
44,44,3060.64,3018.85,3085.12,3017.00,140031.4076,0,1.0,3121.594,3103.418258,...,vertical,2022-04-18 18:16:00,3169.7925,2867.9075,24.0,2022-04-18 07:48:00,1.0,0.5,93.349917,No trade

In [6]:
trades.reset_index(inplace=True, drop=True)

In [7]:
trades.sort_values(by=['datetime'], inplace=True)

/var/folders/9g/0tl60q4d1zbb_1ggbb19w_4c0000gp/T/ipykernel_3702/1065974243.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trades.sort_values(by=['datetime'], inplace=True)

In [8]:
trades.head()

,Unnamed: 0,open,close,high,low,volume,y_pred,to_keep_x,SMA_5,EMA_5,...,barrier_touched,barrier_touched_date,top_barrier,bottom_barrier,time_step,barrier_touched_date_lag,to_keep_y,trade,budget,transaction
0,0,3364.99,3314.78,3388.41,3302.20,107714.8465,1,1.0,3384.336,3369.243540,...,top,2022-04-02 00:51:00,3480.5190,3149.0410,6.0,2022-04-03 22:02:00,1.0,0.0,94.762500,sell
1,6,3466.98,3504.41,3509.77,3426.41,112752.2679,0,1.0,3396.510,3425.400681,...,bottom,2022-04-06 00:14:00,3679.6305,3329.1895,14.0,2022-04-06 01:19:00,1.0,0.5,94.525594,No trade
2,7,3504.42,3451.47,3525.13,3445.00,66491.4051,0,1.0,3430.468,3434.090454,...,bottom,2022-04-06 01:19:00,3624.0435,3278.8965,14.0,2022-04-06 00:14:00,1.0,0.5,94.525594,No trade
3,8,3451.47,3524.94,3528.34,3451.47,163721.0202,0,1.0,3469.292,3464.373636,...,bottom,2022-04-06 00:14:00,3701.1870,3348.6930,12.0,2022-04-06 01:19:00,1.0,0.0,99.003744,sell
4,20,3387.22,3316.95,3392.98,3313.00,34695.0981,0,1.0,3429.788,3400.701830,...,bottom,2022-04-07 04:52:00,3482.7975,3151.1025,9.0,2022-04-06 16:39:00,1.0,0.5,98.756234,No trade

In [224]:
trades = trades[['datetime', 'close', 'barrier_touched','barrier_touched_date', 'top_barrier','bottom_barrier', 'transaction', 'budget']]

In [209]:
config.cost = 0.0025
trades['cost_exit'] = 0
trades['cost_entry'] = 0

In [214]:
for i in trades.index:
    trades.loc[i, 'price_entry'] = trades.loc[i, 'close']

    # prices
    if trades.loc[i, 'transaction'] in ['sell', 'buy']:
        if trades.loc[i, 'barrier_touched'] == 'top':
            trades.loc[i, 'price_exit'] = trades.loc[i, 'top_barrier']
        elif trades.loc[i, 'barrier_touched'] == 'bottom':
            trades.loc[i, 'price_exit'] = trades.loc[i, 'bottom_barrier']
        elif trades.loc[i, 'barrier_touched'] == 'vertical':
            trades.loc[i, 'price_exit'] = trades.loc[i+1, 'close']
    elif trades.loc[i, 'transaction'] == 'No trade':
        trades.loc[i, 'price_exit'] = trades.loc[i+1, 'close']

    # cost
    if i == 0 and trades.loc[i, 'transaction'] in ['sell', 'buy']:
        trades.loc[i, 'cost_entry'] = config.cost
    elif i > 0:
        # if the transaction is different than the previous one
        if trades.loc[i, 'transaction'] != trades.loc[i-1, 'transaction']:
            # if previously there was no transaction, there is no exit cost
            if trades.loc[i-1, 'transaction'] == 'No trade':
                trades.loc[i, 'cost_exit'] = 0
            else:
                trades.loc[i-1, 'cost_exit'] = config.cost
            if trades.loc[i, 'transaction'] in ['sell', 'buy']:
                trades.loc[i, 'cost_entry'] = config.cost
        if i == trades.index[-1] and trades.loc[i, 'transaction'] in ['sell', 'buy']:
            trades.loc[i, 'cost_exit'] = config.cost

In [9]:
trades.head(40)

,Unnamed: 0,open,close,high,low,volume,y_pred,to_keep_x,SMA_5,EMA_5,...,barrier_touched,barrier_touched_date,top_barrier,bottom_barrier,time_step,barrier_touched_date_lag,to_keep_y,trade,budget,transaction
0,0,3364.99,3314.78,3388.41,3302.20,107714.8465,1,1.0,3384.336,3369.243540,...,top,2022-04-02 00:51:00,3480.5190,3149.0410,6.0,2022-04-03 22:02:00,1.0,0.0,94.762500,sell
1,6,3466.98,3504.41,3509.77,3426.41,112752.2679,0,1.0,3396.510,3425.400681,...,bottom,2022-04-06 00:14:00,3679.6305,3329.1895,14.0,2022-04-06 01:19:00,1.0,0.5,94.525594,No trade
2,7,3504.42,3451.47,3525.13,3445.00,66491.4051,0,1.0,3430.468,3434.090454,...,bottom,2022-04-06 01:19:00,3624.0435,3278.8965,14.0,2022-04-06 00:14:00,1.0,0.5,94.525594,No trade
3,8,3451.47,3524.94,3528.34,3451.47,163721.0202,0,1.0,3469.292,3464.373636,...,bottom,2022-04-06 00:14:00,3701.1870,3348.6930,12.0,2022-04-06 01:19:00,1.0,0.0,99.003744,sell
4,20,3387.22,3316.95,3392.98,3313.00,34695.0981,0,1.0,3429.788,3400.701830,...,bottom,2022-04-07 04:52:00,3482.7975,3151.1025,9.0,2022-04-06 16:39:00,1.0,0.5,98.756234,No trade
5,21,3316.94,3343.56,3345.41,3268.00,72661.2489,0,1.0,3389.624,3381.654553,...,bottom,2022-04-06 19:02:00,3510.7380,3176.3820,6.0,2022-04-07 04:52:00,1.0,0.5,98.756234,No trade
6,22,3343.57,3305.10,3373.64,3304.34,150836.0865,0,1.0,3354.844,3356.136369,...,bottom,2022-04-11 09:34:00,3470.3550,3139.8450,20.0,2022-04-06 19:02:00,1.0,0.5,98.756234,No trade
7,23,3305.11,3256.40,3326.19,3256.00,91325.9398,0,1.0,3321.848,3322.890913,...,bottom,2022-04-11 10:03:00,3419.2200,3093.5800,20.0,2022-04-11 09:34:00,1.0,0.5,98.756234,No trade
8,24,3256.27,3190.33,3273.98,3182.00,155434.7259,0,1.0,3282.468,3278.703942,...,bottom,2022-04-11 13:32:00,3349.8465,3030.8135,20.0,2022-04-11 10:03:00,1.0,1.0,93.583877,buy
9,44,3060.64,3018.85,3085.12,3017.00,140031.4076,0,1.0,3121.594,3103.418258,...,vertical,2022-04-18 18:16:00,3169.7925,2867.9075,24.0,2022-04-18 07:48:00,1.0,0.5,93.349917,No trade
10,45,3018.85,2992.06,3058.27,2990.00,99789.1394,1,1.0,3072.208,3066.298839,...,top,2022-04-14 10:58:00,3141.6630,2842.4570,13.0,2022-04-18 18:16:00,1.0,0.5,93.349917,No trade
11,46,2992.05,2977.30,3040.59,2967.00,147388.7216,1,1.0,3033.974,3036.632559,...,top,2022-04-13 22:34:00,3126.1650,2828.4350,11.0,2022-04-14 10:58:00,1.0,0.5,93.349917,No trade
12,47,2977.30,3014.40,3014.78,2950.00,42629.7729,1,1.0,3012.650,3029.221706,...,vertical,2022-04-20 10:42:00,3165.1200,2863.6800,24.0,2022-04-13 22:34:00,1.0,0.5,93.349917,No trade
13,48,3014.41,2953.68,3014.47,2950.92,72030.4495,1,1.0,2991.258,3004.041137,...,top,2022-04-13 22:34:00,3101.3640,2805.9960,9.0,2022-04-20 10:42:00,1.0,0.5,93.349917,No trade
14,49,2953.69,3011.83,3012.47,2950.00,47842.0006,1,1.0,2989.854,3006.637425,...,top,2022-04-20 13:54:00,3162.4215,2861.2385,23.0,2022-04-13 22:34:00,1.0,0.5,93.349917,No trade
15,50,3011.84,3066.39,3073.30,2997.53,159814.8730,0,1.0,3004.720,3026.554950,...,bottom,2022-04-18 07:48:00,3219.7095,2913.0705,15.0,2022-04-20 13:54:00,1.0,0.5,93.349917,No trade
16,51,3066.36,3018.18,3085.00,3016.61,120227.1846,1,1.0,3012.896,3023.763300,...,vertical,2022-04-21 10:40:00,3169.0890,2867.2710,24.0,2022-04-18 07:48:00,1.0,0.5,93.349917,No trade
17,52,3018.19,2998.21,3064.00,2997.04,117525.0412,1,1.0,3009.658,3015.245533,...,top,2022-04-20 13:54:00,3148.1205,2848.2995,20.0,2022-04-21 10:40:00,1.0,0.5,93.349917,No trade
18,53,2998.21,3028.84,3036.55,2967.02,76377.1586,1,1.0,3024.690,3019.777022,...,vertical,2022-04-21 19:02:00,3180.2820,2877.3980,24.0,2022-04-20 13:54:00,1.0,0.5,93.349917,No trade
19,54,3028.83,3068.30,3070.00,3005.50,84493.4979,0,1.0,3035.984,3035.951348,...,bottom,2022-04-18 07:48:00,3221.7150,2914.8850,11.0,2022-04-21 19:02:00,1.0,0.5,93.349917,No trade
20,55,3068.29,3007.27,3068.32,3005.45,96606.1138,1,1.0,3024.160,3026.390899,...,top,2022-04-20 13:54:00,3157.6335,2856.9065,17.0,2022-04-18 07:48:00,1.0,1.0,97.772369,buy
21,72,3129.52,3095.98,3166.50,3086.86,105775.7905,0,1.0,3076.588,3075.684291,...,bottom,2022-04-23 04:22:00,3250.7790,2941.1810,10.0,2022-04-21 22:30:00,1.0,0.5,97.527938,No trade
22,73,3095.99,3039.46,3113.03,3037.08,111056.3394,0,1.0,3081.926,3063.609528,...,bottom,2022-04-25 01:04:00,3191.4330,2887.4870,13.0,2022-04-23 04:22:00,1.0,0.5,97.527938,No trade
23,74,3039.44,3102.00,3102.00,3036.45,87366.3556,0,1.0,3092.250,3076.406352,...,bottom,2022-04-22 04:58:00,3257.1000,2946.9000,6.0,2022-04-25 01:04:00,1.0,0.0,102.148324,sell
24,80,2955.51,3014.85,3014.90,2942.31,119954.7201,0,1.0,3027.770,3020.605482,...,bottom,2022-04-25 01:04:00,3165.5925,2864.1075,6.0,2022-04-25 11:48:00,1.0,0.5,101.892954,No trade
25,81,3014.85,2966.61,3034.32,2964.23,184581.6945,0,1.0,2998.494,3002.606988,...,bottom,2022-04-25 06:58:00,3114.9405,2818.2795,6.0,2022-04-25 01:04:00,1.0,0.5,101.892954,No trade
26,82,2966.62,2918.40,2987.91,2913.89,230071.6538,0,1.0,2971.276,2974.537992,...,bottom,2022-04-27 01:21:00,3064.3200,2772.4800,15.0,2022-04-25 06:58:00,1.0,0.5,101.892954,No trade
27,83,2918.41,2977.96,2978.00,2915.18,96183.4805,0,1.0,2966.664,2975.678661,...,bottom,2022-04-25 06:58:00,3126.8580,2829.0620,4.0,2022-04-27 01:21:00,1.0,0.5,101.892954,No trade
28,84,2977.96,2914.44,2978.03,2912.09,146945.1213,0,1.0,2958.452,2955.265774,...,bottom,2022-04-27 01:21:00,3060.1620,2768.7180,13.0,2022-04-25 06:58:00,1.0,0.5,101.892954,No trade
29,85,2914.45,2904.72,2967.06,2901.46,128653.5060,0,1.0,2936.426,2938.417183,...,vertical,2022-04-29 09:07:00,3049.9560,2759.4840,24.0,2022-04-27 01:21:00,1.0,0.5,101.892954,No trade
30,86,2904.71,2848.36,2908.30,2844.68,54365.7753,1,1.0,2912.776,2908.398122,...,top,2022-04-25 19:58:00,2990.7780,2705.9420,5.0,2022-04-29 09:07:00,1.0,0.5,101.892954,No trade
31,87,2848.35,2820.79,2879.72,2816.25,97583.8029,1,1.0,2893.254,2879.195415,...,top,2022-04-25 18:46:00,2961.8295,2679.7505,3.0,2022-04-25 19:58:00,1.0,0.5,101.892954,No trade
32,88,2820.79,2858.24,2859.71,2797.01,119160.8293,1,1.0,2869.310,2872.210276,...,top,2022-04-25 19:58:00,3001.1520,2715.3280,3.0,2022-04-25 18:46:00,1.0,0.5,101.892954,No trade
33,89,2858.24,2903.09,2905.00,2842.00,153432.0328,0,1.0,2867.040,2882.503518,...,vertical,2022-04-30 02:07:00,3048.2445,2757.9355,24.0,2022-04-25 19:58:00,1.0,0.5,101.892954,No trade
34,90,2903.08,2956.13,2962.07,2896.09,74380.4590,0,1.0,2877.322,2907.045678,...,bottom,2022-04-26 23:18:00,3103.9365,2808.3235,6.0,2022-04-30 02:07:00,1.0,0.5,101.892954,No trade
35,91,2956.12,3014.52,3015.00,2952.93,59638.3687,0,1.0,2910.554,2942.870452,...,bottom,2022-04-26 15:58:00,3165.2460,2863.7940,3.0,2022-04-26 23:18:00,1.0,0.5,101.892954,No trade
36,92,3014.53,2970.31,3039.54,2968.00,220627.0323,0,1.0,2940.458,2952.016968,...,bottom,2022-04-26 23:18:00,3118.8255,2821.7945,4.0,2022-04-26 15:58:00,1.0,0.5,101.892954,No trade
37,93,2970.32,2908.84,2974.27,2908.24,62529.7529,0,1.0,2950.578,2937.624645,...,bottom,2022-04-30 23:02:00,3054.2820,2763.3980,22.0,2022-04-26 23:18:00,1.0,0.5,101.892954,No trade
38,94,2908.85,2856.44,2918.68,2853.76,59780.3657,0,1.0,2941.248,2910.563097,...,bottom,2022-05-01 01:50:00,2999.2620,2713.6180,22.0,2022-04-30 23:02:00,1.0,0.5,101.892954,No trade
39,95,2856.45,2825.00,2885.86,2824.00,120729.2413,1,1.0,2915.022,2882.042065,...,top,2022-04-28 22:26:00,2966.2500,2683.7500,13.0,2022-05-01 01:50:00,1.0,0.5,101.892954,No trade

In [216]:
trades.tail(40)

,datetime,close,barrier_touched,barrier_touched_date,top_barrier,bottom_barrier,transaction,budget,cost_exit,cost_entry,price_entry,price_exit,price_change,return,return_after_cost
367,2022-06-19 10:16:00,1033.44,top,2022-06-19 18:58:00,1085.1120,981.7680,No trade,80.430854,0.0000,0.0000,1033.44,1051.0900,0.017079,0.00,1.000000
368,2022-06-19 10:20:00,1051.09,top,2022-06-19 18:58:00,1103.6445,998.5355,No trade,80.430854,0.0000,0.0000,1051.09,1044.5400,-0.006232,0.00,1.000000
369,2022-06-19 12:27:00,1044.54,top,2022-06-19 18:58:00,1096.7670,992.3130,No trade,80.430854,0.0000,0.0000,1044.54,1023.1200,-0.020507,0.00,1.000000
370,2022-06-19 13:58:00,1023.12,top,2022-06-19 16:49:00,1074.2760,971.9640,No trade,80.430854,0.0000,0.0000,1023.12,1059.4000,0.035460,0.00,1.000000
371,2022-06-19 15:33:00,1059.40,top,2022-06-19 19:06:00,1112.3700,1006.4300,No trade,80.430854,0.0000,0.0000,1059.40,1046.9500,-0.011752,0.00,1.000000
372,2022-06-19 16:49:00,1046.95,top,2022-06-19 18:58:00,1099.2975,994.6025,No trade,80.430854,0.0000,0.0000,1046.95,1065.3000,0.017527,0.00,1.000000
373,2022-06-19 18:16:00,1065.30,top,2022-06-19 19:06:00,1118.5650,1012.0350,No trade,80.430854,0.0000,0.0000,1065.30,1103.9900,0.036318,0.00,1.000000
374,2022-06-19 18:58:00,1103.99,top,2022-06-20 12:02:00,1159.1895,1048.7905,No trade,80.430854,0.0000,0.0000,1103.99,1097.0000,-0.006332,0.00,1.000000
375,2022-06-19 19:06:00,1097.00,top,2022-06-19 21:54:00,1151.8500,1042.1500,No trade,80.430854,0.0000,0.0000,1097.00,1114.0200,0.015515,0.00,1.000000
376,2022-06-19 20:22:00,1114.02,bottom,2022-06-20 03:28:00,1169.7210,1058.3190,sell,84.241266,0.0000,0.0025,1114.02,1058.3190,-0.050000,0.05,1.047375
377,2022-06-20 03:28:00,1079.57,top,2022-06-20 09:10:00,1133.5485,1025.5915,sell,80.029202,0.0000,0.0000,1079.57,1133.5485,0.050000,-0.05,0.950000
378,2022-06-20 09:10:00,1131.27,top,2022-06-21 13:59:00,1187.8335,1074.7065,sell,76.027742,0.0000,0.0000,1131.27,1187.8335,0.050000,-0.05,0.950000
379,2022-06-21 13:59:00,1184.74,bottom,2022-06-21 19:47:00,1243.9770,1125.5030,sell,79.829129,0.0000,0.0000,1184.74,1125.5030,-0.050000,0.05,1.050000
380,2022-06-21 19:47:00,1128.05,bottom,2022-06-22 09:35:00,1184.4525,1071.6475,sell,83.820586,0.0025,0.0000,1128.05,1071.6475,-0.050000,0.05,1.050000
381,2022-06-22 09:35:00,1094.14,top,2022-06-24 02:36:00,1148.8470,1039.4330,No trade,83.611034,0.0000,0.0000,1094.14,1079.2000,-0.013655,0.00,1.000000
382,2022-06-22 12:43:00,1079.20,top,2022-06-23 20:12:00,1133.1600,1025.2400,No trade,83.611034,0.0000,0.0000,1079.20,1093.9000,0.013621,0.00,1.000000
383,2022-06-22 13:27:00,1093.90,top,2022-06-24 02:36:00,1148.5950,1039.2050,No trade,83.611034,0.0000,0.0000,1093.90,1113.1500,0.017598,0.00,1.000000
384,2022-06-22 13:55:00,1113.15,bottom,2022-06-22 16:05:00,1168.8075,1057.4925,No trade,83.611034,0.0000,0.0000,1113.15,1098.6900,-0.012990,0.00,1.000000
385,2022-06-22 15:28:00,1098.69,bottom,2022-06-23 00:14:00,1153.6245,1043.7555,No trade,83.611034,0.0000,0.0000,1098.69,1081.1000,-0.016010,0.00,1.000000
386,2022-06-22 15:55:00,1081.10,top,2022-06-23 20:12:00,1135.1550,1027.0450,sell,79.231906,0.0025,0.0025,1081.10,1135.1550,0.050000,-0.05,0.947625
387,2022-06-23 20:12:00,1140.59,top,2022-06-24 11:33:00,1197.6195,1083.5605,No trade,79.033827,0.0000,0.0000,1140.59,1145.5200,0.004322,0.00,1.000000
388,2022-06-23 22:29:00,1145.52,top,2022-06-24 12:22:00,1202.7960,1088.2440,No trade,79.033827,0.0000,0.0000,1145.52,1165.3100,0.017276,0.00,1.000000
389,2022-06-24 02:36:00,1165.31,top,2022-06-24 14:43:00,1223.5755,1107.0445,buy,82.778054,0.0025,0.0025,1165.31,1223.5755,0.050000,0.05,1.047375
390,2022-06-24 14:43:00,1198.00,top,2022-06-26 12:55:00,1257.9000,1138.1000,No trade,82.571109,0.0000,0.0000,1198.00,1213.0000,0.012521,0.00,1.000000
391,2022-06-24 17:01:00,1213.00,top,2022-06-26 12:55:00,1273.6500,1152.3500,No trade,82.571109,0.0000,0.0000,1213.00,1227.9700,0.012341,0.00,1.000000
392,2022-06-24 19:58:00,1227.97,bottom,2022-06-28 02:13:00,1289.3685,1166.5715,No trade,82.571109,0.0000,0.0000,1227.97,1216.1900,-0.009593,0.00,1.000000
393,2022-06-24 20:58:00,1216.19,top,2022-06-26 12:55:00,1276.9995,1155.3805,No trade,82.571109,0.0000,0.0000,1216.19,1241.1200,0.020498,0.00,1.000000
394,2022-06-24 22:16:00,1241.12,bottom,2022-06-27 18:16:00,1303.1760,1179.0640,No trade,82.571109,0.0000,0.0000,1241.12,1218.9100,-0.017895,0.00,1.000000
395,2022-06-25 00:06:00,1218.91,top,2022-06-26 12:55:00,1279.8555,1157.9645,No trade,82.571109,0.0000,0.0000,1218.91,1232.1900,0.010895,0.00,1.000000
396,2022-06-25 07:15:00,1232.19,bottom,2022-06-28 02:13:00,1293.7995,1170.5805,No trade,82.571109,0.0000,0.0000,1232.19,1213.0700,-0.015517,0.00,1.000000
397,2022-06-25 11:46:00,1213.07,top,2022-06-26 12:55:00,1273.7235,1152.4165,No trade,82.571109,0.0000,0.0000,1213.07,1193.6100,-0.016042,0.00,1.000000
398,2022-06-25 12:28:00,1193.61,top,2022-06-25 21:39:00,1253.2905,1133.9295,No trade,82.571109,0.0000,0.0000,1193.61,1183.5900,-0.008395,0.00,1.000000
399,2022-06-25 15:56:00,1183.59,top,2022-06-25 21:39:00,1242.7695,1124.4105,No trade,82.571109,0.0000,0.0000,1183.59,1208.7500,0.021257,0.00,1.000000
400,2022-06-25 18:55:00,1208.75,top,2022-06-26 12:55:00,1269.1875,1148.3125,sell,78.246447,0.0000,0.0025,1208.75,1269.1875,0.050000,-0.05,0.947625
401,2022-06-26 12:55:00,1250.09,bottom,2022-06-27 18:16:00,1312.5945,1187.5855,sell,82.158770,0.0000,0.0000,1250.09,1187.5855,-0.050000,0.05,1.050000
402,2022-06-27 18:16:00,1202.87,bottom,2022-06-28 23:03:00,1263.0135,1142.7265,sell,86.266708,0.0000,0.0000,1202.87,1142.7265,-0.050000,0.05,1.050000
403,2022-06-28 23:03:00,1144.47,bottom,2022-06-30 01:21:00,1201.6935,1087.2465,sell,90.580043,0.0025,0.0000,1144.47,1087.2465,-0.050000,0.05,1.050000
404,2022-06-30 01:21:00,1081.41,bottom,2022-06-30 10:51:00,1135.4805,1027.3395,No trade,90.353593,0.0000,0.0000,1081.41,1070.9600,-0.009663,0.00,1.000000
405,2022-06-30 06:30:00,1070.96,bottom,2022-06-30 10:51:00,1124.5080,1017.4120,No trade,90.353593,0.0000,0.0000,1070.96,1046.2200,-0.023101,0.00,1.000000
406,2022-06-30 08:24:00,1046.22,top,2022-07-01 00:31:00,1098.5310,993.9090,buy,94.634095,0.0025,0.0025,1046.22,1098.5310,0.050000,0.05,1.047375

In [206]:
trades['price_change'] = trades['price_exit']/trades['price_entry'] - 1
trades['return'] = np.where(trades['transaction']== 'sell', -trades['price_change'], trades['price_change'])
trades['return'] = np.where(trades['transaction']== 'No trade', 0, trades['return'])
trades['return_after_cost'] = np.where(trades['transaction']== 'No trade', 1, 1 * (1-trades['cost_entry']) * (1-trades['cost_exit']) * (1+trades['return']))
trades

,datetime,close,barrier_touched,barrier_touched_date,top_barrier,bottom_barrier,transaction,budget,cost_exit,cost_entry,price_entry,price_exit,price_change,return,return_after_cost
0,2022-03-31 16:22:00,3314.78,top,2022-04-02 00:51:00,3480.5190,3149.0410,sell,94.762500,0.0000,0.0025,3314.78,3480.5190,0.050000,-0.05,0.947625
1,2022-04-02 00:51:00,3504.41,bottom,2022-04-06 00:14:00,3679.6305,3329.1895,No trade,94.525594,0.0025,0.0000,3504.41,3451.4700,-0.015107,0.00,1.000000
2,2022-04-02 02:43:00,3451.47,bottom,2022-04-06 01:19:00,3624.0435,3278.8965,No trade,94.525594,0.0000,0.0000,3451.47,3524.9400,0.021287,0.00,1.000000
3,2022-04-02 12:35:00,3524.94,bottom,2022-04-06 00:14:00,3701.1870,3348.6930,sell,99.003744,0.0000,0.0025,3524.94,3348.6930,-0.050000,0.05,1.047375
4,2022-04-06 00:14:00,3316.95,bottom,2022-04-07 04:52:00,3482.7975,3151.1025,No trade,98.756234,0.0025,0.0000,3316.95,3343.5600,0.008022,0.00,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,2022-06-27 18:16:00,1202.87,bottom,2022-06-28 23:03:00,1263.0135,1142.7265,sell,86.266708,0.0000,0.0000,1202.87,1142.7265,-0.050000,0.05,1.050000
403,2022-06-28 23:03:00,1144.47,bottom,2022-06-30 01:21:00,1201.6935,1087.2465,sell,90.580043,0.0000,0.0000,1144.47,1087.2465,-0.050000,0.05,1.050000
404,2022-06-30 01:21:00,1081.41,bottom,2022-06-30 10:51:00,1135.4805,1027.3395,No trade,90.353593,0.0025,0.0000,1081.41,1070.9600,-0.009663,0.00,1.000000
405,2022-06-30 06:30:00,1070.96,bottom,2022-06-30 10:51:00,1124.5080,1017.4120,No trade,90.353593,0.0000,0.0000,1070.96,1046.2200,-0.023101,0.00,1.000000
406,2022-06-30 08:24:00,1046.22,top,2022-07-01 00:31:00,1098.5310,993.9090,buy,94.634095,0.0000,0.0025,1046.22,1098.5310,0.050000,0.05,1.047375

In [188]:
1*(1-0.0025) * (1+ (-0.05))

0.9452559375000001

In [184]:
budget = 100 * (1-0.0025)
budget

99.75

In [185]:
budget *0.95

94.76249999999999

In [182]:
100 * (1- 0.0025 - 0.05)

94.75

In [180]:
budget = budget + budget * (-0.05)
budget

94.7625

In [181]:
budget = budget * (1-0.0025)
budget

94.52559375000001

In [168]:
0.95-0.0025

0.9475

In [171]:
(100-0.0025) * 0.95  *(1-0.0025)

94.76013093750001

In [167]:
from itertools import accumulate

out = [*accumulate(trades['return_after_cost'].to_list(), lambda a, b: a*b)]
out

[0.9450000000000002,
 0.9450000000000002,
 0.9450000000000002,
 0.9875250000000001,
 0.9875250000000001,
 0.9875250000000001,
 0.9875250000000001,
 0.9875250000000001,
 0.933211125,
 0.933211125,
 0.933211125,
 0.933211125,
 0.933211125,
 0.933211125,
 0.933211125,
 0.933211125,
 0.933211125,
 0.933211125,
 0.933211125,
 0.933211125,
 0.9752056256250001,
 0.9752056256250001,
 0.9752056256250001,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.019089878778125,
 1.0649489233231408,
 1.0649489233231408,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.1128716248726824,
 1.051663685504685,
 1.098988551352396,
 1.0385441810280143,
 1.0385441810280143,
 1.0385441810280143,
 1.0385441810280143,
 1.0385441810280143,
 1.0385441810280143,
 1.0385441810280143,
 1.0385441810280143,
 1.0385441810280143,
 1.0852786691742748,
 1.0852786691742748,
 1.0852786691742748,
 1.0852786691742748,
 1.0852786691742748,
 1.0852786691742748,
 1.0852786691742748,
 1.0852786691742748,
 1.0852786691742748,
 1.0852786691742748,
 1.0852786691742748,
 1.0852786691742748,
 1.0852786691742748,
 1.0852786691742748,
 1.0255883423696897,
 1.0255883423696897,
 1.0255883423696897,
 1.0255883423696897,
 1.0255883423696897,
 1.0255883423696897,
 1.0255883423696897,
 1.0255883423696897,
 1.0717398177763258,
 1.0127941277986279,
 0.9570904507697033,
 0.9044504759773696,
 0.9451507473963514,
 0.8931674562895521,
 0.933359991822582,
 0.9753611914545983,
 0.9217163259245954,
 0.9217163259245954,
 0.9217163259245954,
 0.9217163259245954,
 0.9217163259245954,
 0.9217163259245954,
 0.9217163259245954,
 0.9217163259245954,
 0.9217163259245954,
 0.9217163259245954,
 0.9217163259245954,
 0.9217163259245954,
 0.9217163259245954,
 0.9217163259245954,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8710219279987426,
 0.8231157219588117,
 0.8231157219588117,
 0.8231157219588117,
 0.8231157219588117,
 0.8231157219588117,
 0.8231157219588117,
 0.8231157219588117,
 0.8231157219588117,
 0.8601559294469582,
 0.8601559294469582,
 0.8601559294469582,
 0.8601559294469582,
 0.8601559294469582,
 0.8601559294469582,
 0.8988629462720714,
 0.8988629462720714,
 0.8988629462720714,
 0.8988629462720714,
 0.8988629462720714,
 0.8988629462720714,
 0.8988629462720714,
 0.8988629462720714,
 0.8988629462720714,
 0.8988629462720714,
 0.8988629462720714,
 0.8988629462720714,
 0.8988629462720714,
 0.8988629462720714,
 0.9393117788543147,
 0.9393117788543147,
 0.9393117788543147,
 0.9393117788543147,
 0.9393117788543147,
 0.9393117788543147,
 0.9393117788543147,
 0.9393117788543147,
 0.9393117788543147,
 0.9393117788543147,
 0.8876496310173274,
 0.9275938644131071,
 0.9275938644131071,
 0.9275938644131071,
 0.9275938644131071,
 0.9275938644131071,
 0.9275938644131071,
 0.9275938644131071,
 0.9275938644131071,
 0.9275938644131071,
 0.9275938644131071,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9693355883116969,
 0.9160221309545535,
 0.9572431268475086,
 0.9572431268475086,
 0.9572431268475086,
 0.9572431268475086,
 0.9572431268475086,
 0.9572431268475086,
 0.9572431268475086,
 0.9572431268475086,
 0.9045947548708957,
 0.8548420433529964,
 0.8933099353038814,
 0.8441778888621678,
 0.7977481049747487,
 0.7538719592011374,
 0.7124090014450747,
 0.6732265063655957,
 0.7035216991520475,
 0.6648280056986849,
 0.6648280056986849,
 0.6648280056986849,
 0.6648280056986849,
 0.6648280056986849,
 0.6648280056986849,
 0.6648280056986849,
 0.6648280056986849,
 0.6947452659551259,
 0.6947452659551259,
 0.6947452659551259,
 0.6947452659551259,
 0.6947452659551259,
 0.7260088029231067,
 0.7260088029231067,
 0.7260088029231067,
 0.7586791990546465,
 0.7586791990546465,
 0.7586791990546465,
 0.7586791990546465,
 0.7586791990546465,
 0.7586791990546465,
 0.7169518431066411,
 0.7169518431066411,
 0.7169518431066411,
 0.7169518431066411,
 0.7169518431066411,
 0.7169518431066411,
 0.74921467604644,
 0.7829293364685299,
 0.7398682229627608,
 0.6991754706998089,
 0.7306383668813003,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7635170933909589,
 0.7215236532544561,
 0.7539922176509067,
 0.7125226456801069,
 0.7125226456801069,
 0.6733339001677011,
 0.6363005356584776,
 0.6649340597631092,
 0.6948560924524491,
 0.6566390073675643,
 0.6566390073675643,
 0.6566390073675643,
 0.6566390073675643,
 0.6566390073675643,
 0.6566390073675643,
 0.6566390073675643,
 0.6566390073675643,
 0.6861877626991046,
 0.6861877626991046,
 0.6861877626991046,
 0.6861877626991046,
 0.6861877626991046,
 0.6861877626991046,
 0.6861877626991046,
 0.6861877626991046,
 0.6861877626991046,
 0.6861877626991046,
 0.7170662120205644,
 0.6776275703594332,
 0.6403580539896644,
 0.6691741664191994,
 0.6992870039080633,
 0.6992870039080633,
 0.6992870039080633,
 0.6992870039080633,
 0.6992870039080633,
 0.6992870039080633,
 0.6608262186931197,
 0.6608262186931197,
 0.6608262186931197,
 0.6905633985343103,
 0.6905633985343103,
 0.6905633985343103,
 0.6905633985343103,
 0.6905633985343103,
 0.6905633985343103,
 0.6905633985343103,
 0.6905633985343103,
 0.6905633985343103,
 0.6905633985343103,
 0.6905633985343103,
 0.6525824116149231,
 0.6819486201375948,
 0.7126363080437865,
 0.744704941905757,
 0.744704941905757,
 0.744704941905757,
 0.778216664291516]

In [10]:
df_daily = pd.read_csv('/Users/i0495036/Documents/sandbox/ml_investing_wne/src/ml_investing_wne/data/processed/binance_ETHUSDT/time_aggregated_1440min.csv', parse_dates=['datetime'])

In [11]:
df_daily['datetime'] = pd.to_datetime(df_daily['datetime']) 
df_daily['datetime'] = df_daily['datetime'] +  pd.DateOffset(hours=23) + pd.DateOffset(minutes=59) +  pd.DateOffset(seconds=59)

In [12]:
start_date = backtest['datetime'].min().date()
start_datetime = datetime.datetime.combine(start_date, datetime.time(23, 0, 0))

In [13]:
df_daily = df_daily.loc[df_daily['datetime']>=start_datetime]

In [14]:
df_daily.head(1)

                datetime    open     high      low    close       volume
1550 2022-03-31 23:59:59  3385.8  3444.83  3261.35  3281.51  455091.2395

In [15]:
cols = ['datetime', 'open','close', 'barrier_touched','barrier_touched_date', 'top_barrier','bottom_barrier', 'transaction', 'budget']

In [16]:
df_daily['barrier_touched'] = None
df_daily['barrier_touched_date'] = None
df_daily['top_barrier'] = None
df_daily['bottom_barrier'] = None
df_daily['transaction'] = None
df_daily['budget'] = None

In [17]:
trades_and_close = pd.concat([trades[cols], df_daily[cols]])

In [18]:
trades_and_close

,datetime,open,close,barrier_touched,barrier_touched_date,top_barrier,bottom_barrier,transaction,budget
0,2022-03-31 16:22:00,3364.99,3314.78,top,2022-04-02 00:51:00,3480.5190,3149.0410,sell,94.762500
1,2022-04-02 00:51:00,3466.98,3504.41,bottom,2022-04-06 00:14:00,3679.6305,3329.1895,No trade,94.525594
2,2022-04-02 02:43:00,3504.42,3451.47,bottom,2022-04-06 01:19:00,3624.0435,3278.8965,No trade,94.525594
3,2022-04-02 12:35:00,3451.47,3524.94,bottom,2022-04-06 00:14:00,3701.1870,3348.6930,sell,99.003744
4,2022-04-06 00:14:00,3387.22,3316.95,bottom,2022-04-07 04:52:00,3482.7975,3151.1025,No trade,98.756234
...,...,...,...,...,...,...,...,...,...
2001,2023-06-25 23:59:59,1874.95,1898.80,None,None,NaN,NaN,None,NaN
2002,2023-06-26 23:59:59,1898.80,1858.97,None,None,NaN,NaN,None,NaN
2003,2023-06-27 23:59:59,1858.97,1889.58,None,None,NaN,NaN,None,NaN
2004,2023-06-28 23:59:59,1889.58,1828.02,None,None,NaN,NaN,None,NaN
2005,2023-06-29 23:59:59,1828.03,1851.99,None,None,NaN,NaN,None,NaN

In [19]:
trades_and_close.sort_values(by='datetime', inplace=True)

In [20]:
trades_and_close['transaction'] = trades_and_close['transaction'].ffill()

In [21]:
trades[cols].head(10)

,datetime,open,close,barrier_touched,barrier_touched_date,top_barrier,bottom_barrier,transaction,budget
0,2022-03-31 16:22:00,3364.99,3314.78,top,2022-04-02 00:51:00,3480.5190,3149.0410,sell,94.762500
1,2022-04-02 00:51:00,3466.98,3504.41,bottom,2022-04-06 00:14:00,3679.6305,3329.1895,No trade,94.525594
2,2022-04-02 02:43:00,3504.42,3451.47,bottom,2022-04-06 01:19:00,3624.0435,3278.8965,No trade,94.525594
3,2022-04-02 12:35:00,3451.47,3524.94,bottom,2022-04-06 00:14:00,3701.1870,3348.6930,sell,99.003744
4,2022-04-06 00:14:00,3387.22,3316.95,bottom,2022-04-07 04:52:00,3482.7975,3151.1025,No trade,98.756234
5,2022-04-06 01:19:00,3316.94,3343.56,bottom,2022-04-06 19:02:00,3510.7380,3176.3820,No trade,98.756234
6,2022-04-06 11:11:00,3343.57,3305.10,bottom,2022-04-11 09:34:00,3470.3550,3139.8450,No trade,98.756234
7,2022-04-06 13:48:00,3305.11,3256.40,bottom,2022-04-11 10:03:00,3419.2200,3093.5800,No trade,98.756234
8,2022-04-06 16:39:00,3256.27,3190.33,bottom,2022-04-11 13:32:00,3349.8465,3030.8135,buy,93.583877
9,2022-04-11 13:32:00,3060.64,3018.85,vertical,2022-04-18 18:16:00,3169.7925,2867.9075,No trade,93.349917

In [22]:
trades_and_close.head(30)

,datetime,open,close,barrier_touched,barrier_touched_date,top_barrier,bottom_barrier,transaction,budget
0,2022-03-31 16:22:00,3364.99,3314.78,top,2022-04-02 00:51:00,3480.5190,3149.0410,sell,94.762500
1550,2022-03-31 23:59:59,3385.80,3281.51,None,None,NaN,NaN,sell,NaN
1551,2022-04-01 23:59:59,3281.51,3455.21,None,None,NaN,NaN,sell,NaN
1,2022-04-02 00:51:00,3466.98,3504.41,bottom,2022-04-06 00:14:00,3679.6305,3329.1895,No trade,94.525594
2,2022-04-02 02:43:00,3504.42,3451.47,bottom,2022-04-06 01:19:00,3624.0435,3278.8965,No trade,94.525594
3,2022-04-02 12:35:00,3451.47,3524.94,bottom,2022-04-06 00:14:00,3701.1870,3348.6930,sell,99.003744
1552,2022-04-02 23:59:59,3455.20,3443.77,None,None,NaN,NaN,sell,NaN
1553,2022-04-03 23:59:59,3443.77,3521.91,None,None,NaN,NaN,sell,NaN
1554,2022-04-04 23:59:59,3521.90,3519.50,None,None,NaN,NaN,sell,NaN
1555,2022-04-05 23:59:59,3519.50,3406.99,None,None,NaN,NaN,sell,NaN
4,2022-04-06 00:14:00,3387.22,3316.95,bottom,2022-04-07 04:52:00,3482.7975,3151.1025,No trade,98.756234
5,2022-04-06 01:19:00,3316.94,3343.56,bottom,2022-04-06 19:02:00,3510.7380,3176.3820,No trade,98.756234
6,2022-04-06 11:11:00,3343.57,3305.10,bottom,2022-04-11 09:34:00,3470.3550,3139.8450,No trade,98.756234
7,2022-04-06 13:48:00,3305.11,3256.40,bottom,2022-04-11 10:03:00,3419.2200,3093.5800,No trade,98.756234
8,2022-04-06 16:39:00,3256.27,3190.33,bottom,2022-04-11 13:32:00,3349.8465,3030.8135,buy,93.583877
1556,2022-04-06 23:59:59,3407.00,3168.51,None,None,NaN,NaN,buy,NaN
1557,2022-04-07 23:59:59,3168.52,3227.19,None,None,NaN,NaN,buy,NaN
1558,2022-04-08 23:59:59,3227.20,3192.39,None,None,NaN,NaN,buy,NaN
1559,2022-04-09 23:59:59,3192.39,3258.57,None,None,NaN,NaN,buy,NaN
1560,2022-04-10 23:59:59,3258.57,3203.04,None,None,NaN,NaN,buy,NaN
9,2022-04-11 13:32:00,3060.64,3018.85,vertical,2022-04-18 18:16:00,3169.7925,2867.9075,No trade,93.349917
10,2022-04-11 16:27:00,3018.85,2992.06,top,2022-04-14 10:58:00,3141.6630,2842.4570,No trade,93.349917
11,2022-04-11 21:35:00,2992.05,2977.30,top,2022-04-13 22:34:00,3126.1650,2828.4350,No trade,93.349917
12,2022-04-11 22:42:00,2977.30,3014.40,vertical,2022-04-20 10:42:00,3165.1200,2863.6800,No trade,93.349917
1561,2022-04-11 23:59:59,3203.04,2979.74,None,None,NaN,NaN,No trade,NaN
13,2022-04-12 02:26:00,3014.41,2953.68,top,2022-04-13 22:34:00,3101.3640,2805.9960,No trade,93.349917
14,2022-04-12 05:26:00,2953.69,3011.83,top,2022-04-20 13:54:00,3162.4215,2861.2385,No trade,93.349917
15,2022-04-12 12:30:00,3011.84,3066.39,bottom,2022-04-18 07:48:00,3219.7095,2913.0705,No trade,93.349917
16,2022-04-12 14:27:00,3066.36,3018.18,vertical,2022-04-21 10:40:00,3169.0890,2867.2710,No trade,93.349917
17,2022-04-12 19:03:00,3018.19,2998.21,top,2022-04-20 13:54:00,3148.1205,2848.2995,No trade,93.349917

In [24]:
transaction = No trade

In [ ]:
results = []
for i in trades.index:

    _datetime = trades_and_close.loc[i, 'datetime']
    # open position
    if transaction == 'No trade':
        if trades_and_close.loc[i, 'transaction'] == 'No trade':
            continue
        else:
            _datetime = trades_and_close.loc[i, 'datetime']
            transaction = trades_and_close.loc[i, 'transaction']
            entry_price = trades_and_close.loc[i, 'close']
            exit_position_price = trades_and_close.loc[i, 'exit_price']
            barrier_touched = trades_and_close.loc[i, 'barrier_touched']
            _return = 0
            entry_cost = 0
            exit_cost = 0
            hold_period = 0
            continue
            # results.append([transaction, entry_price, exit_price, barrier_touched, _return, entry_cost, exit_cost, hold_period])
    
    # no change in open position
    if transaction == trades_and_close.loc[i, 'transaction'] and transaction != 'No trade':
        # this means that this is end of the day record
        if trades_and_close.loc[i, 'barrier_touched'] is None:
            if hold_period == 0:
                _return = (trades_and_close.loc[i, 'close'] - entry_price) / entry_price -1
                entry_cost = config.cost
            else:
                _return = (trades_and_close.loc[i, 'close'] - trades_and_close.loc[i, 'open']) / trades_and_close.loc[i, 'open'] -1
                entry_cost = 0
                transaction = 'keep'
                entry_price = trades_and_close.loc[i, 'open']
            exit_cost = 0
            exit_price = trades_and_close.loc[i, 'close']
            hold_period += 1
            results.append([_datetime, transaction, entry_price, exit_price, _return, entry_cost, exit_cost])
            continue
            
        # if current row is intraday record without closing poisition, ignore it     
        else:
            continue
        
    # change in open position
    if transaction != trades_and_close.loc[i, 'transaction'] and transaction != 'No trade':

        # close the position
        
        exit_price = exit_position_price
        _return = exit_price / trades_and_close.loc[i, 'open']
        entry_cost = 0
        exit_cost = config.cost
        results.append([_datetime, transaction, entry_price, exit_price, _return, entry_cost, exit_cost])

        transaction = trades_and_close.loc[i, 'transaction']
        if transaction in ['buy','sell']:
            entry_price = trades_and_close.loc[i, 'close']
            exit_position_price = trades_and_close.loc[i, 'exit_price']
            barrier_touched = trades_and_close.loc[i, 'barrier_touched']
            _return = 0
            entry_cost = config.cost
            exit_cost = 0
            hold_period = 0
            continue

In [23]:
for i in trades.index:
    trades.loc[i, 'price_entry'] = trades.loc[i, 'close']

    # prices
    if trades.loc[i, 'transaction'] in ['sell', 'buy']:
        if trades.loc[i, 'barrier_touched'] == 'top':
            trades.loc[i, 'price_exit'] = trades.loc[i, 'top_barrier']
        elif trades.loc[i, 'barrier_touched'] == 'bottom':
            trades.loc[i, 'price_exit'] = trades.loc[i, 'bottom_barrier']
        elif trades.loc[i, 'barrier_touched'] == 'vertical':
            trades.loc[i, 'price_exit'] = trades.loc[i+1, 'close']
    elif trades.loc[i, 'transaction'] == 'No trade':
        trades.loc[i, 'price_exit'] = trades.loc[i+1, 'close']

/var/folders/9g/0tl60q4d1zbb_1ggbb19w_4c0000gp/T/ipykernel_3702/720416494.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trades.loc[i, 'price_entry'] = trades.loc[i, 'close']
/var/folders/9g/0tl60q4d1zbb_1ggbb19w_4c0000gp/T/ipykernel_3702/720416494.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trades.loc[i, 'price_exit'] = trades.loc[i, 'top_barrier']